# Generated by Django 3.2.23 on 2024-01-15 07:45

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('news', 'News'), ('sports', 'Sports'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('travel', 'Travel')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='News_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('overview', models.TextField(max_length=400)),
                ('meta_keywords', models.TextField(max_length=400)),
                ('thumbnail_url', models.URLField(max_length=1024)),
                ('description', tinymce.models.HTMLField()),
                ('new_blog_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True)),
                ('selected_home_post', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
        ),
    ]
